---
# Shotouts to Piwi's TechTalk for this one

# how to make sure IP's are correct? Web 
- name: Check if swarm is already created
  docker_swarm_info:
    nodes: yes
  register: swarm_info
  ignore_errors: yes
  run_once: true
  delegate_to: "{{ groups['docker-swarm'][0] }}"

# deploy first swarm node
#  when: swarm_info.docker_swarm_active == false or swarm_info.docker_swarm_active is not defined

- include_tasks: deploy_nodes.yml
  when: swarm_info.docker_swarm_active == false or swarm_info.docker_swarm_active is not defined
