---
- name: Replace .env file
  template:
    src: .env.j2
    dest: "{{ jitsi_installation_folder }}/docker-jitsi-meet-stable-5390-1/.env"
    
- name: Create jvb service on a given machine
  docker_swarm_service:
    name: jvb-{{  }}
    
    
  
  
  
