---
# play these tasks for ALL jitsi nodes
#- name: Install gtar
#  apt: name=gtar state=latest update_cache=yes
    

# https://github.com/jitsi/docker-jitsi-meet/archive/refs/tags/stable-5390-1.tar.gz
- name: Make sure folder exists
  file:
    state: directory
    path: "{{ jitsi_installation_folder }}"
    mode: 0775
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Download & extract archive (version is hardcoded!)
  unarchive:
    remote_src: yes
    src: https://github.com/jitsi/docker-jitsi-meet/archive/refs/tags/stable-5390-1.tar.gz
    dest: "{{ jitsi_installation_folder }}"
 
 
  # WARNING: SOME REALLY BAD (BUT CLEVER) CODE (OR WHATEVER) AHEAD
  
- name: Generate random string
  command: openssl rand -hex 16
  register: result
  loop: [1, 2, 3, 4, 5, 6]
  delegate_to: localhost
  run_once: true

- name: Set password variables
  set_fact: "{{ item }}={{ result.results[my_idx].stdout }}"
  loop:
    - jicofo_component_secret
    - jicofo_auth_password
    - jvb_auth_password
    - jigasi_xmpp_password
    - jibri_recorder_password
    - jibri_xmpp_password
  loop_control:
    index_var: my_idx

- name: Creating directories
  command: mkdir -p {{ jitsi_installation_folder }}/.jitsi-meet-cfg/{web/letsencrypt,transcripts,prosody/config,prosody/prosody-plugins-custom,jicofo,jvb,jigasi,jibri}
  

- name: deploy (x) JVBs
  include: deploy_jitsi_jvb.yml
  when: inventory_hostname in groups['jitsi-jvb']
  static: false
  
- name: deploy 1 jitsi-app
  include: deploy_jitsi_app.yml
  when: inventory_hostname in groups['jitsi-app']
  static: false
