---
- name: Installing rocketchat
- hosts: rocketchat
  become: true
  vars_files:
    - vars/installation-consts.yaml
  
  tasks:
    - name: Pull rocket.chat, NGINX, MongoDB, nginx-proxy-companion from dockerhub
      docker-image: 
        name: "{{ item }}"
        source: pull
        pull:
          platform: {{ sys_type }}
      loop: [[ "rocketchat/rocket.chat:{{ rocketchat_tag }}", "mongo:{{ mongo_tag }}", "jwilder/nginx-proxy:{{ jwilder_nginx_tag }}", "jrcs/letsencrypt-nginx-proxy-companion:{{ le_companion_tag }}" ]]
    
    - name: Create directory for NGINX configs
      file:
        path: ~/nginx-config
        state: directory
        mode: '0775'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
    
    # Use variable for domain name and template for config. IP can be retrieved via ansible variable
    - name: Create config for NGINX
      template:
        src: config-templates/rocketchat-nginx.conf.j2
        dest: ~/nginx-config/nginx.conf
        owner: root
        group: root
        mode: '0644'
    
    - name: Create config for letsencrypt-companion
    
    - name: Create networks
    
    - name: Run nginx-proxy-companion with all of the needed stuff
    
    # Use fs mount instead of volume fro conf. We'll need to modify the config every time we start another instance of rocket.chat
    - name: Run NGINX with all of the needed stuff
    
    - name: Run MongoDB with all of the needed stuff
    
    # Use default port
    - name: Run Rocket.Chat with all of the needed stuff
    
    # Run as separate containers or make compose file?
    
