---
- name: Installing rocketchat
- hosts: rocketchat
  become: true
  vars_files:
    - vars/installation-consts.yaml
  
  tasks:
    - name: Pull rocket.chat, NGINX, MongoDB, nginx-proxy-companion from dockerhub
      docker-image: 
        name: "{{ item }}"
        source: pull
        pull:
          platform: {{ sys_type }}
      # Use normal NGINX image w/ le-proxy-companion?
      loop: [[ "rocketchat/rocket.chat:{{ rocketchat_tag }}", "mongo:{{ mongo_tag }}", "jwilder/nginx-proxy:{{ jwilder_nginx_tag }}", "jrcs/letsencrypt-nginx-proxy-companion:{{ le_companion_tag }}" ]]
    
#    - name: Create directory for NGINX configs
#      file:
#        path: ~/nginx-config
#        state: directory
#        mode: '0775'
#        owner: "{{ ansible_user }}"
#        group: "{{ ansible_user }}"
    
    # Use variable for domain name and template for config. IP can be retrieved via ansible variable
#    - name: Create config for NGINX
#      template:
#        src: config-templates/rocketchat-nginx.conf.j2
#        dest: ~/nginx-config/nginx.conf
#        owner: root
#        group: root
#        mode: '0644'
    
#    - name: Create config for letsencrypt-companion
    
#    - name: Create network for Auto-NGINX container
#      docker_network:
#        name: proxy-net
#        attachable: yes
        
    - name: Create network for database
      docker_network:
        name: db-net
        attachable: yes
    
    # --mount/-v --network
    - name: Run NGINX with all of the needed stuff
      docker_container:
        state: present
        name: "proxy"
        # env: 
        image: "jwilder/nginx-proxy:{{ jwilder_nginx_tag }}"
        detach: yes
        volumes: [[ "/var/run/docker.sock:/tmp/docker.sock:ro", "certs:/etc/nginx/certs:ro", "vhost:/etc/nginx/vhost.d", "webroot:/usr/share/nginx/html" ]]
        networks:
          - name: proxy-net
        published_ports: [[ "80:80", "443:443" ]]
        
    
    # Use fs mount instead of volume fro conf. We'll need to modify the config every time we start another instance of rocket.chat
    - name: Run nginx-proxy-companion with all of the needed stuff
      docker_container:
        state: present
        name: "proxy_companion"
        image: "jrcs/letsencrypt-nginx-proxy-companion:{{ le_companion_tag }}"
        env: "DEFAULT_EMAIL={{ le_email | mandatory }}"
        detach: yes
        volumes_from: [[ "proxy" ]]
        volumes: [[ "/var/run/docker.sock:/var/run/docker.sock:ro", "acme:/etc/acme.sh" ]]
        
    # TODO manage Replication/High Availiability
    - name: Run MongoDB with all of the needed stuff
    - import_playbook: setup-mongos.yaml
    
    # Use default port
    # --env "VIRTUAL_HOST=othersubdomain.yourdomain.tld" \
    # --env "VIRTUAL_PORT=3000" \
    # --env "LETSENCRYPT_HOST=othersubdomain.yourdomain.tld" \
    - name: Run Rocket.Chat with all of the needed stuff
    
    # Run as separate containers or make compose file?
    
