---
- name: Installing mongo set
- hosts: rocketchat:mongo
  become: true
  vars_files:
    - vars/installation-consts.yaml
  
  tasks:
    - name: Pull MongoDB
      docker_image: 
        name: "mongo:{{ mongo_tag }}"
        source: pull
        pull:
          platform: {{ sys_type }}
          
    # TODO automatically add keyFile?? 
    # TODO fill etc_hosts
    - name: Run MongoDB
      docker_container:
        state: present
        name: "MongoDB-slave"
        image: "mongo:{{ mongo_tag }}"
        volumes: 
          - /home/core/mongo-files/data:/data/db
          - /home/core/mongo-files:/opt/keyfile
        hostname: "mongo{{ count }}.{{ domain | mandatory }}" # TODO fix
        etc_hosts:
          mongo1.{{ domain | mandatory }}: ?????
          mongo2.{{ domain | mandatory }}: ?????
          mongo3.{{ domain | mandatory }}: ?????
        exposed_ports:
          - "27017:27017"
        detach: yes
        command: --smallFiles --keyFile /opt/keyfile/mongodb-keyfile --replSet "rs0"
