---
- name: Install aptitude using apt
   apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

- name: Install required system packages
  apt: name={{ item }} state=latest update_cache=yes
  loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

- name: Upgrade pip
   pip:
     name: pip
     executable: pip3
     state: latest

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Update apt and install docker-ce
  apt: update_cache=yes name=docker-ce state=latest

- name: Install Docker Modules for Python
  pip:
    name: 
      - docker
      - docker-compose
      - jsondiff
      - pyyaml
      
        
# sudo usermod -aG docker <your-user>
- name: Allow default user to run Docker
  user: name={{ ansible_user }}
        group={{ ansible_user }}
        shell=/bin/bash
        password=${password}
        groups=docker
        append=yes
