---
- name: Create users (db will be created automatically)
  command: docker exec -it mongodb "{{ item }}"
  with_items: 
    - "mongo admin --eval 'db.createUser({ 
    user: \"root\", 
    pwd: \"{{ mongo_useradmin_password }}\", 
    roles: [ 
    { role: \"root\", db: \"admin\" } 
    ]
    });'"
    - "mongo rocketchat -u root -p \"{{ mongo_useradmin_password }}\" --authenticationDatabase admin --eval 'db.createUser({
    user: \"{{ rc_user }}\",
    pwd: \"{{ rc_password }}\",
    roles: [
    {role: \"dbOwner\", db: \"rocketchat\"}, {role: \"readWrite\", db: \"local\"}
    ]
    });'"  
